---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.apiServerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.apiServer.service.type | quote }}
  ports:
  - name: web
    port: 8080
    targetPort: web
    {{- with .Values.apiServer.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector: {{- include "dependencytrack.apiServerSelectorLabels" . | nindent 4 }}