common:
  secretKey:
    createSecret: true

apiServer:
  resources:
    requests:
      cpu: "1"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "512Mi"
  extraEnv:
    SYSTEM_REQUIREMENT_CHECK_ENABLED: "false"
